export const FETCH_RESTAURANTS_START = 'FETCH_RESTAURANTS_START'
export const FETCH_RESTAURANTS_SUCCESS = 'FETCH_RESTAURANTS_SUCCESS'
export const FETCH_RESTAURANTS_ERROR = 'FETCH_RESTAURANTS_ERROR'

export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const FETCH_SPECS_START = 'FETCH_SPECS_START'
export const FETCH_SPECS_SUCCESS = 'FETCH_SPECS_SUCCESS'
export const FETCH_SPECS_ERROR = 'FETCH_SPECS_ERROR'
//USERS
export const FETCH_USERS_START = 'FETCH_USERS_START'
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const FETCH_USERS_ERROR = 'FETCH_USERS_ERROR'

//USER
export const FETCH_USER_START = 'FETCH_USER_START'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR'

export const PUT_USER_START = 'PUT_USER_START'
export const PUT_USER_SUCCESS = 'PUT_USER_SUCCESS'
export const PUT_USER_ERROR = 'PUT_USER_ERROR'

//MENUTYPES
export const CREATE_MENUTYPE_START = 'CREATE_MENUTYPE_START'
export const CREATE_MENUTYPE_SUCCESS = 'CREATE_MENUTYPE_SUCCESS'
export const CREATE_MENUTYPE_ERROR = 'CREATE_MENUTYPE_ERROR'
export const FETCH_MENUTYPES_START = 'FETCH_MENUTYPES_START'
export const FETCH_MENUTYPES_SUCCESS = 'FETCH_MENUTYPES_SUCCESS'
export const FETCH_MENUTYPES_ERROR = 'FETCH_MENUTYPES_ERROR'
export const DELETE_MENUTYPE_START = 'DELETE_MENUTYPE_START'
export const DELETE_MENUTYPE_SUCCESS = 'DELETE_MENUTYPE_SUCCESS'
export const DELETE_MENUTYPE_ERROR = 'DELETE_MENUTYPE_ERROR'
